### ISSUE TITLE
info icon does not work

### ISSUE THREAD

**Issue by cedricjacobs** [a-ui/core_components_react#10]
When trying to use the info icon it does not show up

![image](https://github.com/a-ui/core_components_react/assets/12216776/ae716d95-2246-4f47-a6cb-ac167da0c8f2)

codewise something is awry also when trying to look in the docs

      <div className='icon-grid__icon'>
        <span className='ai ai--thin' aria-hidden='true'>
          <svg>
            <use href='#ai-info'></use>
          </svg>
        </span>
      </div>
      <div className='icon-grid__code'>
        <pre className='a-pre'>ai-info</pre>
      </div>
      <div className='icon-grid__grid-item'>
        <div className='icon-grid__icon'>
          <span className='ai ai--thin' aria-hidden='true'>
            <svg>
              <use href='#ai-iris-scan-1'></use>
            </svg>
          </span>
        </div>

but when copying the code in the docs it looks like this

      <div className='icon-grid__icon'>
        <span className='ai ai--thin' aria-hidden='true'>
          <svg>
            <use
              href='#ai-
                               '
            ></use>
          </svg>
        </span>
      </div>
      <div className='icon-grid__code'>
        <pre className='a-pre'>ai-info</pre>
      </div>
      <div className='icon-grid__grid-item'>
        <div className='icon-grid__icon'>
          <span className='ai ai--thin' aria-hidden='true'>
            <svg>
              <use href='#ai-iris-scan-1'></use>
            </svg>
          </span>
        </div>

**Comment by TriangleJuice** [comment]
Hi @cedricjacobs, can you confirm that you're using the latest versions of **both** core branding and our React components?

**Comment by cedricjacobs** [comment]
"@a-ui/core": "^6.5.0",
    "@a-ui/react": "7.0.3",

**Comment by cedricjacobs** [comment]
7.0.4. is not possible for vite see bug #8

**Comment by TriangleJuice** [comment]
When bug #8 is fixed, this issue will automatically be resolved, so I see no reason to log it as a bug.
