### ISSUE TITLE
State prop on all input components

### ISSUE THREAD

**Issue by SanderVanHullebusch** [a-ui/core_components_react#13]
I noticed that not all input components have a state property. Can this property be added (just like in [TextField](https://github.com/a-ui/core_components_react/blob/development/packages/antwerp-ui/react-components/src/lib/atoms/input/text-field/TextField.tsx)?

**Comment by TriangleJuice** [comment]
@SanderVanHullebusch Could you provide us with more details as why you need/want this feature? Which specific input components are you talking about?
