### ISSUE TITLE
missing key for menu items

### ISSUE THREAD

**Issue by cedricjacobs** [a-ui/core_components_react#9]
in version 7.0.3. the following warning occurs

Warning: Each child in a list should have a unique "key" prop.

Check the render method of Lde. See https://reactjs.org/link/warning-keys for more information.
at Le (file:///Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/node_modules/@a-ui/react/index.mjs:146:10)
at Lde (file:///Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/node_modules/@a-ui/react/index.mjs:39883:26)
at div
at BannerHeader (/Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/src/components/headers/banner-header/banner-header.component.tsx:9:25)

this is the function of which there is a mention in the warning

function Lde({ logoHref: t, logoAlt: e, menuItems: a, logoSrc: r, skipToMainLabel: n, qa: i }) {
return /* @PURE / p("header", { className: "o-header", "data-qa": i, children: / @PURE / V("div", { className: "o-header__content-wrapper", children: [
/ @PURE / V("div", { className: "o-header__content", children: [
/ @PURE / p("a", { href: "#main", className: "a-button a-button--text a-button--neutral o-header__button-skip", children: n }),
/ @PURE / p("a", { href: t, className: "o-header__logo", children: / @PURE / p("img", { src: r, alt: e }) })
] }),
/ @PURE / p("div", { className: "o-header__menu-items", children: (a || []).map(
(o) => o.flyout ? / @PURE / p(
qi,
{
...o.flyout,
trigger: / @PURE / yn(Le, { ...o, key: o.id, emphasis: "low", theme: "neutral", className: "o-header__button" }, o.label)
},
o.id
) : / @PURE */ yn(Le, { ...o, key: o.id, emphasis: "low", theme: "neutral", className: "o-header__button" }, o.label)
) })
] }) });
}
Lde.defaultProps = {
logoHref: "/",
logoAlt: "Naar de startpagina",
logoSrc: "https://cdn.antwerpen.be/core_branding_scss/6.3.0/assets/images/a-logo.svg",
skipToMainLabel: "Ga naar inhoud",
menuItems: []
};

it becomes apparent that a small. tweak is required.

**Comment by cedricjacobs** [comment]
in version 7.0.3. the following warning occurs

Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Lde`. See https://reactjs.org/link/warning-keys for more information.
    at Le (file:///Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/node_modules/@a-ui/react/index.mjs:146:10)
    at Lde (file:///Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/node_modules/@a-ui/react/index.mjs:39883:26)
    at div
    at BannerHeader (/Users/cedricjacobs/Dev/DPA/mpa-frontend-common_package_nodejs/src/components/headers/banner-header/banner-header.component.tsx:9:25)


this is the function of which there is a mention in the warning

function Lde({ logoHref: t, logoAlt: e, menuItems: a, logoSrc: r, skipToMainLabel: n, qa: i }) {
  return /* @__PURE__ */ p("header", { className: "o-header", "data-qa": i, children: /* @__PURE__ */ V("div", { className: "o-header__content-wrapper", children: [
    /* @__PURE__ */ V("div", { className: "o-header__content", children: [
      /* @__PURE__ */ p("a", { href: "#main", className: "a-button a-button--text a-button--neutral o-header__button-skip", children: n }),
      /* @__PURE__ */ p("a", { href: t, className: "o-header__logo", children: /* @__PURE__ */ p("img", { src: r, alt: e }) })
    ] }),
    /* @__PURE__ */ p("div", { className: "o-header__menu-items", children: (a || []).map(
      (o) => o.flyout ? /* @__PURE__ */ p(
        qi,
        {
          ...o.flyout,
          trigger: /* @__PURE__ */ yn(Le, { ...o, key: o.id, emphasis: "low", theme: "neutral", className: "o-header__button" }, o.label)
        },
        o.id
      ) : /* @__PURE__ */ yn(Le, { ...o, key: o.id, emphasis: "low", theme: "neutral", className: "o-header__button" }, o.label)
    ) })
  ] }) });
}
Lde.defaultProps = {
  logoHref: "/",
  logoAlt: "Naar de startpagina",
  logoSrc: "https://cdn.antwerpen.be/core_branding_scss/6.3.0/assets/images/a-logo.svg",
  skipToMainLabel: "Ga naar inhoud",
  menuItems: []
};


it becomes apparent that a small. tweak is required.

**Comment by TriangleJuice** [comment]
This was added in the docs.
